# -*- coding: utf-8 -*-
# """exercises_xpgold.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1NGYjZZs9u7oems7hWTxpVwk5p481JXrA

# #Exercises XP Gold
# """

# """**Exercise 1: Concatenate lists**

# Write code that concatenates two lists together without using the + sign.



a = [2,5,7,9]
b = [1,3,4,8]

# Element-wise addition
print("Addition:", a + b)

# """**Exercise 2: Range of numbers**

# Create a loop that goes from 1500 to 2500 and prints all multiples of 5 and 7.


# """

data = range(1500,2501)
data_df = (data)

multiples = data_df[(data_df[0] % 5 == 0) and (data_df[0] % 7 == 0)]
multiples

# """**Exercise 3: Check the index**

# Using this variable

# names = ['Samus', 'Cortana', 'V', 'Link', 'Mario', 'Cortana', 'Samus']

# Ask a user for their name, if their name is in the names list print out the index of the first occurence of the name.
# """

names = ['Samus', 'Cortana', 'V', 'Link', 'Mario', 'Cortana', 'Samus']

user_name = input("What is your name? ")
if user_name in names:
  print(names.index(user_name))

# """**Exercise 4: Greatest Number**

# Ask the user for 3 numbers and print the greatest number.
# """

user_input_str = input("Enter 3 numbers separated by commas (e.g., 1,2,3): ")

list_of_strings = user_input_str.split(',')

list_of_numbers = [int(num.strip()) for num in list_of_strings]

s = (list_of_numbers)
print("The max number is:", max(s))

"""**Exercise 5: The Alphabet**

Create a string of all the letters in the alphabet

Loop over each letter and print a message that contains the letter and whether its a vowel or a consonant.
"""

letters_string = 'abcdefghijklmnopqrstuvwxyz'
letters_list = list(letters_string)

for letter in letters_list:
  if letter in 'aeiou':
    print(letter, "is a vowel")
  else:
    print(letter, "is a consonant")

"""**Exercise 6: Words and letters**

Ask a user for 7 words, store them in a list named words.

Ask the user for a single character, store it in a variable called letter.

Loop through the words list and print the index of the first appearence of the letter variable in each word of the list.

If the letter doesn’t exist in one of the words, print a friendly message with the word and the letter.
"""

words_input = input("Enter 7 words separated by commas: ")
words = [word.strip() for word in words_input.split(',')]

letter = input("Enter a single character: ")

for word in words:
  if letter in word:
    print(f"The letter '{letter}' first appears at index {word.index(letter)} in the word '{word}'.")
  else:
    print(f"The letter '{letter}' does not exist in the word '{word}'.")

"""**Exercise 7: Min, Max, Sum**

Create a list of numbers from one to one million and then use min() and max() to make sure your list actually starts at one and ends at one million. Use the sum() function to see how quickly Python can add a million numbers.
"""

list_of_numbers = list(range(1,1000001))
print(min(list_of_numbers))

print(max(list_of_numbers))

print(sum(list_of_numbers))

"""**Exercise 8 : List and Tuple**

Write a program which accepts a sequence of comma-separated numbers. Generate a list and a tuple which contain every number.

Suppose the following input is supplied to the program: 34,67,55,33,12,98
"""

num_list= list(input("Enter numbers separated by commas: ").split(','))
print(num_list)

num_tuple = tuple(num_list)
print(num_tuple)

# """**Exercise 9 : Random number**

# Ask the user to input a number from 1 to 9 (including).

# Get a random number between 1 and 9. Hint: random module.
# If the user guesses the correct number print a message that says Winner.

# If the user guesses the wrong number print a message that says better luck next time.

# Bonus: use a loop that allows the user to keep guessing until they want to quit.

# Bonus 2: on exiting the loop tally up and display total games won and lost.
# """

import random

import random

wins = 0
losses = 0

while True:
  try:
    user_input = input("Enter a number from 1 to 9 (or 'q' to quit): ")
    if user_input.lower() == 'q':
      break

    user_guess = int(user_input)

    if not (1 <= user_guess <= 9):
      print("Please enter a number between 1 and 9.")
      continue

    random_number = random.randint(1, 9)

    if user_guess == random_number:
      print("Winner!")
      wins += 1
    else:
      print(f"Better luck next time. The number was {random_number}.")
      losses += 1
  except ValueError:
    print("Invalid input. Please enter a number or 'q' to quit.")

print(f"\nGame Over!\nTotal Wins: {wins}\nTotal Losses: {losses}")