# -*- coding: utf-8 -*-
"""W3D2DC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X7NQWZM6lCqeoK0acA5ZnnSZtMO-dACN

#Daily Challenge: Hands-On Image Transformation and Visualization

Load and Visualize Images using the Flower Color Images dataset

Download the dataset and unzip to use it

# Task
Please upload your `kaggle.json` file again, then the Kaggle dataset 'flower-color-images' will be downloaded and unzipped.
"""

from google.colab import files
files.upload()

!pip install tensorflow
!pip install keras
!pip install pillow
!pip install matplotlib

import zipfile
import os

file_name = '/content/Flower Color Images Dataset.zip'
with zipfile.ZipFile(file_name, 'r') as zip_ref:
    zip_ref.extractall('Flower Color Images Dataset')

# List the contents of the extracted folder to verify
os.listdir('Flower Color Images Dataset/Flower Color Images Dataset')

import os

# Path to the directory containing image files
image_dir = 'Flower Color Images Dataset/Flower Color Images Dataset/flowers/flowers'

# List all files in the directory
image_files = os.listdir(image_dir)

# Filter for common image file extensions (e.g., .png, .jpg, .jpeg)
image_files = [f for f in image_files if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

print(f"Found {len(image_files)} image files in '{image_dir}'.")
print("First 5 image files:", image_files[:5])

from PIL import Image
import matplotlib.pyplot as plt

flower1 = 'Flower Color Images Dataset/Flower Color Images Dataset/flowers/flowers/19_010.png'
original_image = Image.open(flower1)

# Display the original image using matplotlib
plt.imshow(original_image)
plt.title('Original Image')
plt.axis('off') # Hide axes for cleaner image display
plt.show()

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# Convert the PIL Image to a NumPy array
image_array = np.array(original_image)

# Rotate the image array
rotated_image_array = rotate_image_30_degrees(image_array)

# Convert the NumPy array back to a PIL Image
rotated_image = Image.fromarray(rotated_image_array.astype(np.uint8))

# Display the rotated image
plt.imshow(rotated_image)
plt.title('Rotated Image (30 Degrees)')
plt.axis('off')
plt.show()

flower2 = 'Flower Color Images Dataset/Flower Color Images Dataset/flowers/flowers/03_018.png'
original_image = Image.open(flower2)

# Display the original image using matplotlib
plt.imshow(original_image)
plt.title('Original Image')
plt.axis('off') # Hide axes for cleaner image display
plt.show()

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

def flip_image_horizontally(image_array):
    """Flips an image horizontally."""
    return np.fliplr(image_array)

# Convert the PIL Image to a NumPy array
image_array = np.array(original_image)

# Flip the image horizontally
flipped_image_array = flip_image_horizontally(image_array)

# Convert the NumPy array back to a PIL Image
flipped_image = Image.fromarray(flipped_image_array.astype(np.uint8))

# Display the flipped image
plt.imshow(flipped_image)
plt.title('Horizontally Flipped Image')
plt.axis('off')
plt.show()

flower3 = 'Flower Color Images Dataset/Flower Color Images Dataset/flowers/flowers/17_001.png'
original_image = Image.open(flower3)

# Display the original image using matplotlib
plt.imshow(original_image)
plt.title('Original Image')
plt.axis('off') # Hide axes for cleaner image display
plt.show()

from PIL import Image
import matplotlib.pyplot as plt

# Get current dimensions
width, height = original_image.size

# Calculate new dimensions for 1.2x zoom
zoom_factor = 1.2
new_width = int(width * zoom_factor)
new_height = int(height * zoom_factor)

# Resize the image
zoomed_image = original_image.resize((new_width, new_height), Image.LANCZOS)

# Display the zoomed image
plt.imshow(zoomed_image)
plt.title(f'Zoomed Image ({zoom_factor}x)')
plt.axis('off')
plt.show()

